CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "email" varchar(255) UNIQUE,
  "phone_number" varchar(20),
  "role" varchar(20),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "description" text,
  "date" datetime,
  "location" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "ticket_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" int,
  "name" varchar(255),
  "description" text,
  "price" decimal(10,2),
  "total_tickets" int,
  "available_tickets" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "event_id" int,
  "status" varchar(20),
  "total_price" decimal(10,2),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "booking_details" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "ticket_type_id" int,
  "quantity" int,
  "price" decimal(10,2),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "tickets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_detail_id" int,
  "qr_code" varchar(255),
  "sent_at" timestamp,
  "checked_in_at" timestamp
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int,
  "amount" decimal(10,2),
  "payment_method" varchar(50),
  "payment_status" varchar(20),
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "admins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "ticket_types" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "booking_details" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id");

ALTER TABLE "booking_details" ADD FOREIGN KEY ("ticket_type_id") REFERENCES "ticket_types" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("booking_detail_id") REFERENCES "booking_details" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id");

ALTER TABLE "admins" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
